name: 29915_test

on:
  # only on pushing to github-rep
  push:
    branches: [ main ]

jobs:

  # checking if .py file with tests exists
  check-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check if tests exist
        run: |
          if [ ! -f test_main.py ]; then
            echo "test_main.py NOT FOUND" > napaka.txt
            exit 1
          else
            > napaka.txt
          fi

      - name: Upload artifact (napaka)
        uses: actions/upload-artifact@v4
        with:
          name: napaka
          path: napaka.txt

  run-tests:
    needs: check-tests # only if check-tests successed
    runs-on: self-hosted

    strategy:
      matrix: # using matrix- testing on different versions of python
        python-version: [ 3.11, 3.12 ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: napaka

      - name: Check error file
        run: |
          if [ -s napaka.txt ]; then
            echo "ERROR: tests missing or broken"
            cat napaka.txt
            exit 1
          fi

      - name: Create venv and install deps
        run: |
          ${{ matrix.python-version }} -m venv venv
          source venv/bin/activate
          python -m pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          python -m pytest -v